// Code generated by "stringer -type Cardinality"; DO NOT EDIT.

package gel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoResult-110]
	_ = x[AtMostOne-111]
	_ = x[One-65]
	_ = x[Many-109]
	_ = x[AtLeastOne-77]
}

const (
	_Cardinality_name_0 = "One"
	_Cardinality_name_1 = "AtLeastOne"
	_Cardinality_name_2 = "ManyNoResultAtMostOne"
)

var (
	_Cardinality_index_2 = [...]uint8{0, 4, 12, 21}
)

func (i Cardinality) String() string {
	switch {
	case i == 65:
		return _Cardinality_name_0
	case i == 77:
		return _Cardinality_name_1
	case 109 <= i && i <= 111:
		i -= 109
		return _Cardinality_name_2[_Cardinality_index_2[i]:_Cardinality_index_2[i+1]]
	default:
		return "Cardinality(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
