// Code generated by "stringer -type Message"; DO NOT EDIT.

package gel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Authentication-82]
	_ = x[CommandComplete-67]
	_ = x[CommandDataDescription-84]
	_ = x[Data-68]
	_ = x[DumpBlock-61]
	_ = x[DumpHeader-64]
	_ = x[ErrorResponse-69]
	_ = x[LogMessage-76]
	_ = x[ParameterStatus-83]
	_ = x[ParseComplete-49]
	_ = x[ReadyForCommand-90]
	_ = x[RestoreReady-43]
	_ = x[ServerHandshake-118]
	_ = x[ServerKeyData-75]
	_ = x[StateDataDescription-115]
	_ = x[AuthenticationSASLInitialResponse-112]
	_ = x[AuthenticationSASLResponse-114]
	_ = x[ClientHandshake-86]
	_ = x[DescribeStatement-68]
	_ = x[Dump-62]
	_ = x[Execute0pX-69]
	_ = x[ExecuteScript-81]
	_ = x[Flush-72]
	_ = x[Execute-79]
	_ = x[Parse-80]
	_ = x[Restore-60]
	_ = x[RestoreBlock-61]
	_ = x[RestoreEOF-46]
	_ = x[Sync-83]
	_ = x[Terminate-88]
}

const _Message_name = "RestoreReadyRestoreEOFParseCompleteRestoreDumpBlockDumpDumpHeaderCommandCompleteDataErrorResponseFlushServerKeyDataLogMessageExecuteParseExecuteScriptAuthenticationParameterStatusCommandDataDescriptionClientHandshakeTerminateReadyForCommandAuthenticationSASLInitialResponseAuthenticationSASLResponseStateDataDescriptionServerHandshake"

var _Message_map = map[Message]string{
	43:  _Message_name[0:12],
	46:  _Message_name[12:22],
	49:  _Message_name[22:35],
	60:  _Message_name[35:42],
	61:  _Message_name[42:51],
	62:  _Message_name[51:55],
	64:  _Message_name[55:65],
	67:  _Message_name[65:80],
	68:  _Message_name[80:84],
	69:  _Message_name[84:97],
	72:  _Message_name[97:102],
	75:  _Message_name[102:115],
	76:  _Message_name[115:125],
	79:  _Message_name[125:132],
	80:  _Message_name[132:137],
	81:  _Message_name[137:150],
	82:  _Message_name[150:164],
	83:  _Message_name[164:179],
	84:  _Message_name[179:201],
	86:  _Message_name[201:216],
	88:  _Message_name[216:225],
	90:  _Message_name[225:240],
	112: _Message_name[240:273],
	114: _Message_name[273:299],
	115: _Message_name[299:319],
	118: _Message_name[319:334],
}

func (i Message) String() string {
	if str, ok := _Message_map[i]; ok {
		return str
	}
	return "Message(" + strconv.FormatInt(int64(i), 10) + ")"
}
