name: Build .rst Docs

concurrency: docs-build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "rstdocs/**"

jobs:
  docsbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build rst docs
        run: make gendocs

      - name: Push docs changes
        shell: bash
        run: ./.github/workflows/push-docs.sh
